[cargo-new]
vcs = "none" # do not automatically create git repo

# Make cargo quiet, more UNIX-like
[term]
quiet = true
verbose = false
progress.when = "never"

[build]
# WARN: be careful deploying stuff built locally
rustflags = ["-Ctarget-cpu=native"]
