# add_field
# Autogenerated from man page /usr/local/share/man/man1/add_field.1
complete -c add_field -s h -l help --description 'print this message and exit.'
complete -c add_field -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c add_field -s f -l field --description 'the 1-based index for the new field (default: 1).'
complete -c add_field -s B -l Before --description 'place the new field before the field with the specified label.'
complete -c add_field -s A -l After --description 'place the new field after the field with the specified label.'
complete -c add_field -s l -l label --description 'specifies the first-line label for the new field.'
complete -c add_field -s v -l value --description 'the value to place in the new field (default: emtpy).'
complete -c add_field -s c -l copy --description 'specifies an existing field to copy into the new field.'

