# adig
# Autogenerated from man page /usr/local/share/man/man1/adig.1
complete -c adig -s c --description 'Set the query class.'
complete -c adig -s d --description 'Print some extra debugging output.'
complete -c adig -s f --description 'Add a flag.'
complete -c adig -s h -l help --description 'Display this help and exit.'
complete -c adig -s T --description 'Use specified TCP port to connect to DNS server.'
complete -c adig -s s --description 'Connect to specified DNS server, instead of the system\'s default one(s).'
complete -c adig -s t --description 'Query records of specified type.'
complete -c adig -s U --description 'Use specified UDP port to connect to DNS server.'

