# aggregate2
# Autogenerated from man page /usr/local/share/man/man1/aggregate2.1
complete -c aggregate2 -s h -l help --description 'print this message and exit.'
complete -c aggregate2 -s V -l version --description 'print version info and exit.'
complete -c aggregate2 -s v -l verbose --description 'print verbose messages during execution.'
complete -c aggregate2 -s d -l delim --description 'field separator string.'
complete -c aggregate2 -s p -l preserve-header --description 'do not treat first line as data.'
complete -c aggregate2 -s k -l keys --description 'indexes of aggregation keys.'
complete -c aggregate2 -s K -l key-labels --description 'labels of aggregation key.'
complete -c aggregate2 -s s -l sums --description 'indexes of fields to be summed.'
complete -c aggregate2 -s S -l sum-labels --description 'labels of fields to be summed.'
complete -c aggregate2 -s c -l counts --description 'indexes of fields to be counted if non-blank.'
complete -c aggregate2 -s C -l count-labels --description 'labels of fields to be counted if non-blank.'
complete -c aggregate2 -s o -l outfile --description 'file to which output should be written (default: stdout).'
complete -c aggregate2 -s l -l labels --description 'delimiter-separated list of labels for the aggregation fields (default: uncha…'
complete -c aggregate2 -s L -l auto-label --description 'add "-Sum" or "-Count" suffixes to aggregation fields.'

