# apfs_unlockfv
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/apfs_unlockfv.8
complete -c apfs_unlockfv -s h --description 'Print a usage message.'

