# buffer
# Autogenerated from man page /usr/local/share/man/man1/buffer.1
complete -c buffer -s h -l help --description 'print this message and exit.'
complete -c buffer -s o --description 'specifies output file for writing.'
complete -c buffer -s a --description 'specifies if the output file should be appended to.'

