# c++filt
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/c++filt.1
complete -c c++filt -l format -s s --description 'Mangling scheme to assume.'
complete -c c++filt -l help -s h --description 'Print a summary of command line options.'
complete -c c++filt -l help-list --description 'Print an uncategorized summary of command line options.'
complete -c c++filt -l strip-underscore -s _ --description 'Discard a single leading underscore, if present, from each input name before …'
complete -c c++filt -l types -s t --description 'Attempt to demangle names as type names as well as function names.'
complete -c c++filt -l version --description 'Display the version of the llvm-cxxfilt executable.'

