# calcfield
# Autogenerated from man page /usr/local/share/man/man1/calcfield.1
complete -c calcfield -s h -l help --description 'print this message and exit.'
complete -c calcfield -s V -l Version --description 'show version information and exit.'
complete -c calcfield -s v -l verbose --description 'print verbose messages during execution.'
complete -c calcfield -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c calcfield -s p -l preserve-header --description 'preserve the header line (just passes the first line through to the output fi…'
complete -c calcfield -s r -l replace --description 'replace the value at the given index (instead of adding a new column).'
complete -c calcfield -s i -l insert --description 'index for the new fields (1-based); if not given the new field will be append…'
complete -c calcfield -s B -l Before --description 'place the new field before the field with the specified label.'
complete -c calcfield -s A -l After --description 'place the new field after the field with the specified label.'
complete -c calcfield -s e -l expression --description 'the expression to calculate (see below).'
complete -c calcfield -s b -l fallback --description 'if the formula is not properly evaluated use this result as the fallback.'
complete -c calcfield -s c -l new-label --description 'the name of the column for the calculated field; implies -p.'

