# classkit-tool
# Autogenerated from man page /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man/man8/classkit-tool.8
complete -c classkit-tool -s h --description 'Show this message and exit.'
complete -c classkit-tool -s s --description 'Return the current development mode.'
complete -c classkit-tool -s d --description 'Set the development mode to off, teacher, or student.'
complete -c classkit-tool -s r --description 'Reset the development mode data.'

