# convdate
# Autogenerated from man page /usr/local/share/man/man1/convdate.1
complete -c convdate -s h -l help --description 'print this message and exit.'
complete -c convdate -s V -l version --description 'print version info and exit.'
complete -c convdate -s v -l verbose --description 'print verbose runtime messages and warnings.'
complete -c convdate -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c convdate -s f -l field --description '1-based number of field to convert (default: 1).'
complete -c convdate -s F -l field-label --description 'header label of field to convert.'
complete -c convdate -s i -l input_format --description 'date format in the input file - see strptime (default: %%m-%%d-%%Y-%%T).'
complete -c convdate -s o -l output_format --description 'date format in the output file - see strftime (default: %%Y-%%m-%%d-%%T).'
complete -c convdate -s p -l preserve_header --description 'preserve the header line (default: do not preserve the header).'

