# csvformat
# Autogenerated from man page /usr/local/share/man/man1/csvformat.1
complete -c csvformat -s h -l help --description 'print this message and exit.'
complete -c csvformat -s d -l delim --description 'input field separator string (default: 0xfe).'
complete -c csvformat -s i -l input --description 'input file (default: stdin).'
complete -c csvformat -s o -l output --description 'output file (default: stdout).'
complete -c csvformat -s n -l no-escape --description 'do not escape internal quotes.'
complete -c csvformat -s q -l quoting --description 'field quoting style.  Must be one of "all", "minimal", "nonnumeric" or "none".'
complete -c csvformat -s f -l fields-to-quote --description 'only/always quote these specific fields.'

