# csvprintf
# Autogenerated from man page /usr/local/share/man/man1/csvprintf.1
complete -c csvprintf -s e --description 'Specify input character encoding.  By default, ISO-8859-1 is assumed.'
complete -c csvprintf -s f --description 'Read CSV input from the specified file.'
complete -c csvprintf -s i --description 'Ignore the very first CSV record in the input (typically contains column name…'
complete -c csvprintf -s q --description 'Specify an alternate CSV column quote character.'
complete -c csvprintf -s s --description 'Specify an alternate CSV column separator character.'
complete -c csvprintf -s h --description 'Output usage message and exit.'
complete -c csvprintf -s v --description 'Output version information and exit.'
complete -c csvprintf -s x --description 'Convert the CSV input into an XML document.'
complete -c csvprintf -s X --description 'Same as x, but it also causes the values in the first row to be used as the X…'

