# cutfield
# Autogenerated from man page /usr/local/share/man/man1/cutfield.1
complete -c cutfield -s h -l help --description 'print this message and exit.'
complete -c cutfield -s V -l version --description 'print version info and exit.'
complete -c cutfield -s d -l delimiter --description 'field-separator string.'
complete -c cutfield -s f -l field --description 'list of indexes of fields to be removed.'
complete -c cutfield -s F -l field-labels --description 'list of labels of fields to be removed.'
complete -c cutfield -s o -l output-file --description 'name of file to which output should be written.'
complete -c cutfield -s a -l append-file --description 'name of file to which output should be appended.'

