# dates_in_range
# Autogenerated from man page /usr/local/share/man/man1/dates_in_range.1
complete -c dates_in_range -s h -l help --description 'print this message and exit.'
complete -c dates_in_range -s s -l start --description 'beginning of the range.'
complete -c dates_in_range -s e -l end --description 'end of the range.'
complete -c dates_in_range -s f -l format --description 'alternate output date format.'
complete -c dates_in_range -s i -l increment --description 'specifies the number of days by which to increment.'

