# dbstream
# Autogenerated from man page /usr/local/share/man/man1/dbstream.1
complete -c dbstream -s h -l help --description 'print this message and exit.'
complete -c dbstream -l delimiter --description 'field separator string (default: 0xfe).'
complete -c dbstream -s f -l file --description 'run sql specified in this file.'
complete -c dbstream -s s -l sql --description 'run sql specified here.'
complete -c dbstream -s i -l input --description 'file containing placeholder values for insert/update statements.'
complete -c dbstream -s o -l output --description 'write to specified file instead of stdout.'
complete -c dbstream -l dsn --description 'DBI-style data source name.'
complete -c dbstream -l uid --description 'database username.'
complete -c dbstream -l pwd --description 'database password.'

