# deltadays
# Autogenerated from man page /usr/local/share/man/man1/deltadays.1
complete -c deltadays -s h -l help --description 'print this message and exit.'
complete -c deltadays -s s -l start --description 'start date of range.'
complete -c deltadays -s e -l end --description 'end date of range.'
complete -c deltadays -s f -l format --description 'date format to use (default: YYYY-MM-DD).'

