# deltaforce
# Autogenerated from man page /usr/local/share/man/man1/deltaforce.1
complete -c deltaforce -s h -l help --description 'print this message and exit.'
complete -c deltaforce -s V -l version --description 'print version info and exit.'
complete -c deltaforce -s v -l verbose --description 'print verbose messages during execution.'
complete -c deltaforce -s d -l delim --description 'delimiting string for both input files.'
complete -c deltaforce -s o -l outfile --description 'name of file for output.'
complete -c deltaforce -s k -l keys --description 'indexes of primary key field(s) in both input files (default: 1).'
complete -c deltaforce -s K -l key-labels --description 'labels of primary key field(s) in both input files.'

