# dig
# Autogenerated from man page /usr/local/share/man/man1/dig.1
complete -c dig -s r --description 'Do not read options from ${HOME}/. digrc.'
complete -c dig -s u --description 'Print query times in microseconds instead of milliseconds.'

