# dpkg-distaddfile
# Autogenerated from man page /usr/local/share/man/man1/dpkg-distaddfile.1
complete -c dpkg-distaddfile -o ffiles-list-file --description 'Read or write the list of files to be uploaded here, rather than using debian…'
complete -c dpkg-distaddfile -s '?' -l help --description 'Show the usage message and exit.'

