# dpkg-realpath
# Autogenerated from man page /usr/local/share/man/man1/dpkg-realpath.1
complete -c dpkg-realpath -l instdir --description 'Set the installation directory, which refers to the directory where packages …'
complete -c dpkg-realpath -l root --description 'Set the root directory to directory, which sets the installation directory to…'
complete -c dpkg-realpath -s '?' -l help --description 'Show the usage message and exit.'

