# dpkg-mergechangelogs
# Autogenerated from man page /usr/local/share/man/man1/dpkg-mergechangelogs.1
complete -c dpkg-mergechangelogs -s m -l merge-prereleases --description 'Drop the part after the last tilde in the version number when doing version c…'
complete -c dpkg-mergechangelogs -l help --description 'Show the usage message and exit.'

