# enchant-lsmod-2
# Autogenerated from man page /usr/local/share/man/man1/enchant-lsmod-2.1
complete -c enchant-lsmod-2 -o lang --description 'Show which provider and dictionary will be used for the given language, or al…'
complete -c enchant-lsmod-2 -o word-chars --description 'Show the extra word characters for the given language, if available.'
complete -c enchant-lsmod-2 -o list-dicts --description 'List the provider and dictionary for all available languages.'
complete -c enchant-lsmod-2 -o help --description 'Show brief help.'
complete -c enchant-lsmod-2 -o version --description 'Prints the program\'s version.'

