# fieldsplit
# Autogenerated from man page /usr/local/share/man/man1/fieldsplit.1
complete -c fieldsplit -s h -l help --description 'print this message and exit.'
complete -c fieldsplit -s V -l version --description 'print version info and exit.'
complete -c fieldsplit -s f -l field --description 'index of field to split on.'
complete -c fieldsplit -s F -l field-label --description 'label of field to split on.'
complete -c fieldsplit -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c fieldsplit -s p -l path --description 'directory in which output files should be placed (default: . /).'
complete -c fieldsplit -s n -l name --description 'output file prefix.'
complete -c fieldsplit -s s -l suffix --description 'output file suffix.'
complete -c fieldsplit -s k -l keep --description 'preserve the input header row in all output files.'
complete -c fieldsplit -s S -l buffer-lines --description 'line buffer size - DEPRECATED.'
complete -c fieldsplit -s b -l buckets --description 'split data into BUCKETS files, guaranteeing that like field values are in the…'
complete -c fieldsplit -s x -l xform-names --description 'user-supplied substitution regex to transform output names (e. g.'

