# filterkeys
# Autogenerated from man page /usr/local/share/man/man1/filterkeys.1
complete -c filterkeys -s h -l help --description 'print this message and exit.'
complete -c filterkeys -s V -l version --description 'print version info and exit.'
complete -c filterkeys -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c filterkeys -s f -l filter-file --description 'one key per line file used for filtering input.'
complete -c filterkeys -s o -l outfile --description 'output file name (default: stdout).'
complete -c filterkeys -s a -l filter-keys --description 'filter-file field indexes considered for filtering.'
complete -c filterkeys -s b -l file-keys --description 'input-files field indexes considered for filtering.'
complete -c filterkeys -s K -l labels --description 'labels to be considered for filtering.'
complete -c filterkeys -s v -l invert --description 'print only non-matching lines.'
complete -c filterkeys -s p -l preserve_header --description 'preserve the header line of the first file and discard all other headers.'

