# find_not_processed
# Autogenerated from man page /usr/local/share/man/man1/find_not_processed.1
complete -c find_not_processed -s h -l help --description 'print this message and exit.'
complete -c find_not_processed -s d -l directory --description 'directory to look for files in (required).'
complete -c find_not_processed -s l -l logfile --description 'file containing names of already-processed files (required).'
complete -c find_not_processed -s p -l print-dir --description 'print the full file path (default: just the name).'
complete -c find_not_processed -s g -l glob --description 'only look for files matching this shell-style pattern.'
complete -c find_not_processed -s r -l regex --description 'only look for files matching this regular expression.'

