# findfiles
# Autogenerated from man page /usr/local/share/man/man1/findfiles.1
complete -c findfiles -s h -l help --description 'print this message and exit.'
complete -c findfiles -s d -l directory --description 'directory containing files (required).'
complete -c findfiles -s g -l glob --description 'shell-style file pattern to look for.'
complete -c findfiles -s p -l pattern --description 'regular expression for filtering files (default: dd-dd-dddd).'
complete -c findfiles -s s -l start --description 'beginning of date range to include (required).'
complete -c findfiles -s e -l end --description 'end of date range to include (required).'

