# foreach_parallel
# Autogenerated from man page /usr/local/share/man/man1/foreach_parallel.1
complete -c foreach_parallel -s h -l help --description 'print this message and exit.'
complete -c foreach_parallel -s V -l verbose --description 'print verbose runtime messages.'
complete -c foreach_parallel -s v -l variable --description 'the variable name to hold the input value.'
complete -c foreach_parallel -s l -l limit --description 'the maximum number of processes to spawn at one time.'
complete -c foreach_parallel -s f -l file --description 'execute code read from <file> (default: stdin).'

