# funiq
# Autogenerated from man page /usr/local/share/man/man1/funiq.1
complete -c funiq -s h -l help --description 'print this message and exit.'
complete -c funiq -s V -l version --description 'print version info and exit.'
complete -c funiq -s v -l verbose --description 'print verbose messages during execution.'
complete -c funiq -s d -l delimiter --description 'field separator (default: 0xfe).'
complete -c funiq -s f -l fields --description 'indexes of fields to consider in the deduplication.'
complete -c funiq -s F -l field-labels --description 'labels of fields to consider in the deduplication.'
complete -c funiq -s c -l count --description 'produce a count of duplicated lines.'

