# gaccessdb
# Autogenerated from man page /usr/local/share/man/man8/gaccessdb.8
complete -c gaccessdb -s d -l debug --description 'Print debugging information.'
complete -c gaccessdb -s '?' -l help --description 'Print a help message and exit.'
complete -c gaccessdb -l usage --description 'Print a short usage message and exit.'
complete -c gaccessdb -s V -l version --description 'Display version information.  AUTHOR.'

