# gcatman
# Autogenerated from man page /usr/local/share/man/man8/gcatman.8
complete -c gcatman -s d -l debug --description 'Print debugging information.'
complete -c gcatman -s M -l manpath --description 'Specify an alternate colon-delimited manual page hierarchy search path.'
complete -c gcatman -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c gcatman -s '?' -l help --description 'Print a help message and exit.'
complete -c gcatman -l usage --description 'Print a short usage message and exit.'
complete -c gcatman -s V -l version --description 'Display version information.  ENVIRONMENT.'

