# git-show
# Autogenerated from man page /usr/local/share/man/man1/git-show.1
complete -c git-show -l date --description 'unless another.'
complete -c git-show -l decorate --description 'and.'
complete -c git-show -l walk-reflogs --description 'oc o 2. 3.'
complete -c git-show -l no-relative --description '.'

