# git-release
# Autogenerated from man page /usr/local/share/man/man1/git-release.1
complete -c git-release -l semver --description 'If the latest tag in your repo matches the semver format requirement, you cou…'
complete -c git-release -s r --description 'The "remote" repository that is destination of a push operation: it is passed…'
complete -c git-release -s m --description 'use the custom commit information instead of the default message "Release <ta…'
complete -c git-release -l no-empty-commit --description 'Avoid creating empty commit if nothing could be committed.'
complete -c git-release -s c --description 'Generates or populates the changelog with all commit message since the last t…'
complete -c git-release -s s --description 'Create a signed and annotated tag.'
complete -c git-release -s u --description 'Create a tag, annotated and signed with the given key.  [--] hook arguments.'

