# git-diff-tree
# Autogenerated from man page /usr/local/share/man/man1/git-diff-tree.1
complete -c git-diff-tree -l no-relative --description 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-diff-tree -l date --description 'unless another.'
complete -c git-diff-tree -l decorate --description 'and.'
complete -c git-diff-tree -l walk-reflogs --description 'oc o 2. 3.'

