# git-diff-files
# Autogenerated from man page /usr/local/share/man/man1/git-diff-files.1
complete -c git-diff-files -l no-relative --description 'When run from a subdirectory of the project, it can be told to exclude change…'

