# git-restore
# Autogenerated from man page /usr/local/share/man/man1/git-restore.1
complete -c git-restore -l recurse-submodules -l no-recurse-submodules --description 'If <pathspec> names an active submodule and the restore location includes the…'
complete -c git-restore -l pathspec-from-file --description 'Pathspec is passed in <file> instead of commandline args.'
complete -c git-restore -l pathspec-file-nul --description 'Only meaningful with --pathspec-from-file.'
complete -c git-restore -l literal-pathspecs --description '.'

