# git-log
# Autogenerated from man page /usr/local/share/man/man1/git-log.1
complete -c git-log -l mailmap --description 'Use mailmap file to map author and committer names and email addresses to can…'
complete -c git-log -l show-pulls --description 'Include all commits from the default mode, but also any merge commits that ar…'
complete -c git-log -l diff-merges -l no-diff-merges --description '.'
complete -c git-log -l no-relative --description '.'

