# git-bisect
# Autogenerated from man page /usr/local/share/man/man1/git-bisect.1
complete -c git-bisect -l first-parent --description 'Follow only the first parent commit upon seeing a merge commit.'

