# git-format-patch
# Autogenerated from man page /usr/local/share/man/man1/git-format-patch.1
complete -c git-format-patch -l relative -l no-relative --description 'When run from a subdirectory of the project, it can be told to exclude change…'
complete -c git-format-patch -l cover-from-description --description 'Controls which parts of the cover letter will be automatically populated usin…'
complete -c git-format-patch -l encode-email-headers -l no-encode-email-headers --description 'Encode email headers that have non-ASCII characters with "Q-encoding" (descri…'
complete -c git-format-patch -l no-base --description 'option overrides a format. useAutoBase configuration.'

