# git-index-pack
# Autogenerated from man page /usr/local/share/man/man1/git-index-pack.1
complete -c git-index-pack -l object-format --description 'Specify the given object format (hash algorithm) for the pack.'

