# git-config
# Autogenerated from man page /usr/local/share/man/man1/git-config.1
complete -c git-config -l show-scope --description 'Similar to --show-origin in that it augments the output of all queried config…'
complete -c git-config -l max-new-filters --description 'option of git commit-graph write (c. f. , git-commit-graph(1)).  commitGraph.'
complete -c git-config -l cover-from-description --description 'option in git-format-patch(1).  format. signature.'
complete -c git-config -l decorate-refs-exclude --description 'command-line option, but the config option can be overridden by the.'
complete -c git-config -l decorate-refs --description 'option.  log. follow.'
complete -c git-config -l task --description 'option is specified to git maintenance run.'
complete -c git-config -l auto --description 'option.  A negative value will force the task to run every time.'
complete -c git-config -l auto-merge --description 'is given, meld will merge all non-conflicting parts automatically, highlight …'
complete -c git-config -l no-recurse-submodules --description 'option.'
complete -c git-config -l filter --description 'when <n> is no more than the value of uploadpackfilter. tree. maxDepth.'

