# git-info
# Autogenerated from man page /usr/local/share/man/man1/git-info.1
complete -c git-info -s c -l color --description 'Use color for information titles.'
complete -c git-info -l no-config --description 'Don\'t show list all variables set in config file, along with their values.'

