# git-annotate
# Autogenerated from man page /usr/local/share/man/man1/git-annotate.1
complete -c git-annotate -l first-parent --description 'Follow only the first parent commit upon seeing a merge commit.'

