# git-pull
# Autogenerated from man page /usr/local/share/man/man1/git-pull.1
complete -c git-pull -l no-gpg-sign --description 'GPG-sign the resulting merge commit.'
complete -c git-pull -l dry-run --description 'Show what would be done, without making any changes.'
complete -c git-pull -s p -l prune --description 'Before fetching, remove any remote-tracking references that no longer exist o…'
complete -c git-pull -l refmap --description 'When fetching refs listed on the command line, use the specified refspec (can…'
complete -c git-pull -s t -l tags --description 'Fetch all tags from the remote (i. e.'
complete -c git-pull -s j -l jobs --description 'Number of parallel children to be used for all forms of fetching.'
complete -c git-pull -l set-upstream --description 'If the remote is fetched successfully, add upstream (tracking) reference, use…'
complete -c git-pull -l prune-tags --description 'is a shorthand for providing the tag refspec.'
complete -c git-pull -l multiple --description 'option was specified, the different remotes will be fetched in parallel.'

