# git-diff
# Autogenerated from man page /usr/local/share/man/man1/git-diff.1
complete -c git-diff -l no-relative --description 'When run from a subdirectory of the project, it can be told to exclude change…'

