# git-summary
# Autogenerated from man page /usr/local/share/man/man1/git-summary.1
complete -c git-summary -l dedup-by-email --description 'Remove duplicate authors who belong to the same email address.  For example,.'
complete -c git-summary -l line --description 'Summarize with lines other than commits.'

