# git-reset
# Autogenerated from man page /usr/local/share/man/man1/git-reset.1
complete -c git-reset -l pathspec-from-file --description 'Pathspec is passed in <file> instead of commandline args.'
complete -c git-reset -l pathspec-file-nul --description 'Only meaningful with --pathspec-from-file.'
complete -c git-reset -l recurse-submodules --description '.'
complete -c git-reset -l literal-pathspecs --description '.'

