# git-undo
# Autogenerated from man page /usr/local/share/man/man1/git-undo.1
complete -c git-undo -l soft -s s --description 'Rolls back the commit(s) but leaves the changes in the staging area.'
complete -c git-undo -l hard -s h --description 'This option wipes your commit(s), so that your changes cannot be recovered.'

