# git-commit
# Autogenerated from man page /usr/local/share/man/man1/git-commit.1
complete -c git-commit -l pathspec-from-file --description 'Pathspec is passed in <file> instead of commandline args.'
complete -c git-commit -l pathspec-file-nul --description 'Only meaningful with --pathspec-from-file.'
complete -c git-commit -l literal-pathspecs --description '.'

