# glexgrog
# Autogenerated from man page /usr/local/share/man/man1/glexgrog.1
complete -c glexgrog -s d -l debug --description 'Print debugging information.'
complete -c glexgrog -s m -l man --description 'Parse input as man page source files.'
complete -c glexgrog -s c -l cat --description 'Parse input as preformatted man pages (\\(lqcat pages\\(rq).'
complete -c glexgrog -s w -l whatis --description 'Display the name and description from the man page\'s header, as used by  apro…'
complete -c glexgrog -s f -l filters --description 'Display the list of filters needed to preprocess the man page before formatti…'
complete -c glexgrog -s E -l encoding --description 'Override the guessed character set for the page to R encoding .'
complete -c glexgrog -s '?' -l help --description 'Print a help message and exit.'
complete -c glexgrog -l usage --description 'Print a short usage message and exit.'
complete -c glexgrog -s V -l version --description 'Display version information.  EXIT STATUS.'

