# gmanpath
# Autogenerated from man page /usr/local/share/man/man1/gmanpath.1
complete -c gmanpath -s q -l quiet --description 'Do not issue warnings.'
complete -c gmanpath -s d -l debug --description 'Print debugging information.'
complete -c gmanpath -s c -l catpath --description 'Produce a catpath as opposed to a manpath.'
complete -c gmanpath -s g -l global --description 'Produce a manpath consisting of all paths named as "global" within the man-db…'
complete -c gmanpath -s m --description '--systems=system\\|[\\|,. \\|. \\|.'
complete -c gmanpath -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c gmanpath -s '?' -l help --description 'Print a help message and exit.'
complete -c gmanpath -l usage --description 'Print a short usage message and exit.'
complete -c gmanpath -l systems --description 'If this system has access to other operating system\'s manual hierarchies, thi…'
complete -c gmanpath -s V -l version --description 'Display version information.  ENVIRONMENT.'

