# gmanconv
# Autogenerated from man page /usr/local/share/man/man1/gmanconv.1
complete -c gmanconv -s f -l from-code --description 'Try each of  encodings (a colon-separated list) in sequence as the input enco…'
complete -c gmanconv -s t -l to-code --description 'Convert the manual page to R encoding .'
complete -c gmanconv -s q -l quiet --description 'Do not issue error messages when the page cannot be converted.'
complete -c gmanconv -s d -l debug --description 'Print debugging information.'
complete -c gmanconv -s h -l help --description 'Print a help message and exit.'
complete -c gmanconv -s V -l version --description 'Display version information.'

