# gmandb
# Autogenerated from man page /usr/local/share/man/man8/gmandb.8
complete -c gmandb -s d -l debug --description 'Print debugging information.'
complete -c gmandb -s q -l quiet --description 'Produce no warnings.'
complete -c gmandb -s s -l no-straycats --description 'Do not spend time looking for or adding information to the databases regardin…'
complete -c gmandb -s p -l no-purge --description 'Do not spend time checking for deleted manual pages and purging them from the…'
complete -c gmandb -s c -l create --description 'By default,  gmandb will try to update any previously created databases.'
complete -c gmandb -s u -l user-db --description 'Create user databases only, even with write permissions necessary to create s…'
complete -c gmandb -s t -l test --description 'Perform correctness checks on manual pages in the hierarchy search path.'
complete -c gmandb -s f -l filename --description 'Update only the entries for the given filename.'
complete -c gmandb -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c gmandb -s '?' -l help --description 'Show the usage message, then exit.'
complete -c gmandb -l usage --description 'Print a short usage message and exit.'
complete -c gmandb -s V -l version --description 'Show the version, then exit.  EXIT STATUS.'

