# gnutls-certtool
# Autogenerated from man page /usr/local/share/man/man1/gnutls-certtool.1
complete -c gnutls-certtool -l generate-privkey -l generate-dh-params --description '.'
complete -c gnutls-certtool -l load-ca-certificate --description '$ certtool --load-ca-certificate ca. pem    --load-certificate cert.'

