# grepfield
# Autogenerated from man page /usr/local/share/man/man1/grepfield.1
complete -c grepfield -s h -l help --description 'print this message and exit.'
complete -c grepfield -s V -l version --description 'print version info and exit.'
complete -c grepfield -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c grepfield -s o -l outfile --description 'output file name (default: stdout).'
complete -c grepfield -s f -l field --description 'index of field to scan (1-based).'
complete -c grepfield -s F -l field-label --description 'label of field to scan (1-based).'
complete -c grepfield -s v -l invert --description 'print only non-matching lines.'
complete -c grepfield -s i -l ignore-case --description 'do case-insensitive matches.'
complete -c grepfield -s p -l preserve_header --description 'preserve the header line of the first file and discard all other headers.'

