# gwhatis
# Autogenerated from man page /usr/local/share/man/man1/gwhatis.1
complete -c gwhatis -s d -l debug --description 'Print debugging information.'
complete -c gwhatis -s v -l verbose --description 'Print verbose warning messages.'
complete -c gwhatis -s r -l regex --description 'Interpret each  name as a regular expression.'
complete -c gwhatis -s w -l wildcard --description 'Interpret each  name as a pattern containing shell style wildcards.'
complete -c gwhatis -s l -l long --description 'Do not trim output to the terminal width.'
complete -c gwhatis -s s --description '--sections=list\\/, \\ --section=list Search only the given manual sections.'
complete -c gwhatis -s m --description '--systems=system\\|[\\|,. \\|. \\|.'
complete -c gwhatis -s M -l manpath --description 'Specify an alternate set of colon-delimited manual page hierarchies to search.'
complete -c gwhatis -s L -l locale --description 'gwhatis will normally determine your current locale by a call to the C functi…'
complete -c gwhatis -s C -l config-file --description 'Use this user configuration file rather than the default of R ~/. manpath .'
complete -c gwhatis -s '?' -l help --description 'Print a help message and exit.'
complete -c gwhatis -l usage --description 'Print a short usage message and exit.'
complete -c gwhatis -l sections --description '.'
complete -c gwhatis -l section --description 'Search only the given manual sections.'
complete -c gwhatis -l systems --description 'If this system has access to other operating system\'s manual page names, they…'
complete -c gwhatis -s V -l version --description 'Display version information.  EXIT STATUS.'

