# gzsoelim
# Autogenerated from man page /usr/local/share/man/man1/gzsoelim.1
complete -c gzsoelim -s C -l compatible --description 'This flag is available for compatibility with other  soelim programs.'
complete -c gzsoelim -s h -l help --description 'Print a help message and exit.'
complete -c gzsoelim -s V -l version --description 'Display version information.'

