# hashjoin
# Autogenerated from man page /usr/local/share/man/man1/hashjoin.1
complete -c hashjoin -s h -l help --description 'print this message and exit.'
complete -c hashjoin -s V -l version --description 'print version info and exit.'
complete -c hashjoin -s d -l delim --description 'input data field separator string.'
complete -c hashjoin -s f -l dimension-file --description 'the file containing dimensional data.'
complete -c hashjoin -s D -l dimension-delim --description 'dimension file field separator string (if different from the data stream deli…'
complete -c hashjoin -s k -l data-keys --description 'a list of lookup key field indexes in the data stream.'
complete -c hashjoin -s l -l lookup-keys --description 'a list of lookup key field indexes in the dimension file.'
complete -c hashjoin -s K -l key-labels --description 'a list of lookup key field labels.'
complete -c hashjoin -s j -l joined-fields --description 'a list of dimensional field indexes to add to the data.'
complete -c hashjoin -s J -l joined-labels --description 'a list of dimensional field labels to add to the data.'
complete -c hashjoin -s L -l label-dimensions --description 'output labels for added fields when the data stream has a header and the dime…'
complete -c hashjoin -s m -l default-values --description 'comma-separated list of values to use when the dimension file does not have a…'

