# heif-thumbnailer
# Autogenerated from man page /usr/local/share/man/man1/heif-thumbnailer.1
complete -c heif-thumbnailer -s s --description 'Defines the maximum width and height of the thumbnail to generate.'

