# host
# Autogenerated from man page /usr/local/share/man/man1/host.1
complete -c host -s A --description '"Almost all".'
complete -c host -s p --description 'Specify the port on the server to query.  The default is 53.'
complete -c host -o 'T;' -s U --description 'TCP/UDP: By default, host uses UDP when making queries.'

