# iftop
# Autogenerated from man page /usr/local/share/man/man8/iftop.8
complete -c iftop -s h --description 'Print a summary of usage.'
complete -c iftop -s n --description 'Don\'t do hostname lookups.'
complete -c iftop -s N --description 'Do not resolve port number to service names.'
complete -c iftop -s p --description 'Run in promiscuous mode, so that traffic which does not pass directly through…'
complete -c iftop -s P --description 'Turn on port display.'
complete -c iftop -s l --description 'Display and count datagrams addressed to or from link-local IPv6 addresses.'
complete -c iftop -s b --description 'Don\'t display bar graphs of traffic.'
complete -c iftop -s m --description 'Set the upper limit for the bandwidth scale.'
complete -c iftop -s B --description 'Display bandwidth rates in bytes/sec rather than bits/sec.'
complete -c iftop -s i --description 'Listen to packets on interface.'
complete -c iftop -s f --description 'Use filter code to select the packets to count.'
complete -c iftop -s F --description 'Specifies an IPv4 network for traffic analysis.'
complete -c iftop -s G --description 'Specifies an IPv6 network for traffic analysis.'
complete -c iftop -s c --description 'Specifies an alternate config file.   If not specified, iftop will use ~/.'
complete -c iftop -s t --description 'Use text interface without ncurses and print the output to STDOUT.  DISPLAY.'

