# indexof
# Autogenerated from man page /usr/local/share/man/man1/indexof.1
complete -c indexof -s h -l help --description 'print this message and exit.'
complete -c indexof -s V -l version --description 'print version info and exit.'
complete -c indexof -s v -l verbose --description 'print verbose messages during execution.'
complete -c indexof -s d -l delim --description 'field separator string.'
complete -c indexof -s l -l label --description 'the header label to look for (required).'
complete -c indexof -s f -l file --description 'specifies file to read (default = stdin).'
complete -c indexof -s s -l string --description 'use <string> instead of a header from a file.'
complete -c indexof -s r -l row --description 'header line number in file (default = 1).'

