# kak
# Autogenerated from man page /usr/local/share/man/man1/kak.1.gz
complete -c kak -o help --description 'display a help message and quit.'
complete -c kak -o version --description 'display kakoune version and quit.'
complete -c kak -s n --description 'do not load resource files on startup (kakrc, autoload, rc etc).'
complete -c kak -s l --description 'list existing sessions.'
complete -c kak -s d --description 'run as a headless session (requires -s).'
complete -c kak -s e --description 'execute command after the client initialization phase.'
complete -c kak -s E --description 'execute command after the server initialization phase.'
complete -c kak -s f --description 'enter in filter mode: select the whole file, then execute keys.'
complete -c kak -s i --description 'backup the files on which a filter is applied using the given suffix.'
complete -c kak -s q --description 'when in filter mode, don\'t print any errors.'
complete -c kak -s p --description 'send the commands written on the standard input to session session_id.'
complete -c kak -s c --description 'connect to the given session.'
complete -c kak -s s --description 'set the current session name to session_id.'
complete -c kak -o ui --description 'select the user interface, can be one of ncurses, dummy or json.'
complete -c kak -o clear --description 'remove sessions that terminated in an incorrect state (e. g.  after a crash).'
complete -c kak -o ro --description 'enter in readonly mode, all the buffers opened will not be written to disk.'

