# LocateMe
# Autogenerated from man page /usr/local/share/man/man1/LocateMe.1
complete -c LocateMe -s g --description 'Generate a Google Map URL.'
complete -c LocateMe -s h --description 'This help message.'
complete -c LocateMe -s l --description 'Generate long, multiline format.'
complete -c LocateMe -s f --description 'Generate a custom output with the following placeholders: . RS . PP.'

