# mergekeys
# Autogenerated from man page /usr/local/share/man/man1/mergekeys.1
complete -c mergekeys -s h -l help --description 'print this message and exit.'
complete -c mergekeys -s V -l version --description 'print version info and exit.'
complete -c mergekeys -s v -l verbose --description 'print verbose messages during execution.'
complete -c mergekeys -s a -l left-keys --description 'list of key fields in left-hand file.'
complete -c mergekeys -s A -l left-labels --description 'list of key labels in left-hand file.'
complete -c mergekeys -s b -l right-keys --description 'list of key fields in right-hand file.'
complete -c mergekeys -s B -l right-labels --description 'list of key labels in right-hand file.'
complete -c mergekeys -s i -l inner --description 'inner join - i. e.  drop lines that do not have a match in both files.'
complete -c mergekeys -s r -l right --description 'right outer join - i. e.'
complete -c mergekeys -s l -l left --description 'left outer join - i. e.'
complete -c mergekeys -s D -l default --description 'for outer joins, the defaut value to put in unmatched merge fields.'
complete -c mergekeys -s d -l delim --description 'delimiting string for both input files.'
complete -c mergekeys -s o -l outfile --description 'name of file for output.'

