# mmdblookup
# Autogenerated from man page /usr/local/share/man/man1/mmdblookup.1
complete -c mmdblookup -s f --description 'The path to the MMDB file.  Required.'
complete -c mmdblookup -s i --description 'The IP address to look up.  Required.'
complete -c mmdblookup -s v --description 'Turns on verbose output.'
complete -c mmdblookup -s h -s '?' --description 'Show usage information.  BUG REPORTS AND PULL REQUESTS.'

