# nsupdate
# Autogenerated from man page /usr/local/share/man/man1/nsupdate.1
complete -c nsupdate -s 4 --description 'Use IPv4 only.'
complete -c nsupdate -s 6 --description 'Use IPv6 only.'
complete -c nsupdate -s i --description 'Force interactive mode, even when standard input is not a terminal.'

