# ntp-wait
# Autogenerated from man page /usr/local/share/man/man8/ntp-wait.8
complete -c ntp-wait -o '\\&?' --description 'Display usage information and exit.'
complete -c ntp-wait -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c ntp-wait -s v --description 'Output version of program and exit.'

