# ntpd
# Autogenerated from man page /usr/local/share/man/man8/ntpd.8
complete -c ntpd -o '\\&?' --description 'Display usage information and exit.'
complete -c ntpd -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c ntpd -o '\\-version' --description 'Output version of program and exit.'

