# ntpdc
# Autogenerated from man page /usr/local/share/man/man8/ntpdc.8
complete -c ntpdc -o '\\&?' --description 'Display usage information and exit.'
complete -c ntpdc -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c ntpdc -s '>' --description 'Save the option state to \\fIcfgfile\\fP.'
complete -c ntpdc -s '<' --description 'Load options from \\fIcfgfile\\fP.'
complete -c ntpdc -o '\\-version' --description 'Output version of program and exit.'

