# pagestuff
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/pagestuff.1
complete -c pagestuff -o arch --description 'Specifies the architecture,  arch_type, of the file for  pagestuff to operate…'
complete -c pagestuff -o pagesize --description 'Specifies the page size to use when computing logical page boundaries.'
complete -c pagestuff -s a --description 'Display all pages in the file.'
complete -c pagestuff -s p --description 'Print a list of the sections of the specified file, offsets and lengths.'

