# patch
# Autogenerated from man page /usr/local/share/man/man1/patch.1
complete -c patch -l Write --description '/dev/tty .'
complete -c patch -l Merge --description 'merge(1).'
complete -c patch -l When --description 'has been applied already by trying to reverse-apply the first hunk.   The.'
complete -c patch -l -R --description '.'
complete -c patch -l Behave --description 'potential problem, warn about it (the default), or fail.'
complete -c patch -l Produce --description 'unified).'
complete -c patch -l - --description '.'

