# pivot
# Autogenerated from man page /usr/local/share/man/man1/pivot.1
complete -c pivot -s h -l help --description 'print this message and exit.'
complete -c pivot -s V -l version --description 'print version info and exit.'
complete -c pivot -s d -l delimiter --description 'field separator string.'
complete -c pivot -s k -l keep-header --description 'indicates that the first line of input should be treated as header info.'
complete -c pivot -s f -l output-fields --description 'indexes of row fields to output.'
complete -c pivot -s F -l output-labels --description 'labels of row fields to output.'
complete -c pivot -s p -l pivot-fields --description 'indexes of column fields to pivot on.'
complete -c pivot -s P -l pivot-labels --description 'labels of column fields to pivot on.'
complete -c pivot -s v -l value-fields --description 'indexes of data fields to put into the pivoted cells.'
complete -c pivot -s A -l value-labels --description 'labels of data fields to put into the pivoted cells.'

