# po4a-normalize
# Autogenerated from man page /usr/local/share/man/man1/po4a-normalize.1p.gz
complete -c po4a-normalize -s o -l option --description 'Extra option(s) to pass to the format plugin.'
complete -c po4a-normalize -s b -l blank --description 'Create an blank translated document.'
complete -c po4a-normalize -s h -l help --description 'Show a short help message.'
complete -c po4a-normalize -l help-format --description 'List the documentation formats understood by po4a.'
complete -c po4a-normalize -s f -l format --description 'Format of the documentation you want to handle.'
complete -c po4a-normalize -s M -l master-charset --description 'Charset of the file containing the document to translate.'
complete -c po4a-normalize -s l -l localized --description 'Name of the normalized file to produce (po4a-normalize. output by default).'
complete -c po4a-normalize -s p -l pot --description 'Pot file to produce (po4a-normalize. po by default).'

