# po4a-display-man
# Autogenerated from man page /usr/local/share/man/man1/po4a-display-man.1.gz
complete -c po4a-display-man -s p --description 'The PO file containing the translations.'
complete -c po4a-display-man -s m --description 'The original man page.'
complete -c po4a-display-man -s o --description 'Some options to pass to po4a-translate(1).'

