# po4a-gettextize
# Autogenerated from man page /usr/local/share/man/man1/po4a-gettextize.1p.gz
complete -c po4a-gettextize -s f -l format --description 'Format of the documentation you want to handle.'
complete -c po4a-gettextize -s m -l master --description 'File containing the master document to translate.'
complete -c po4a-gettextize -s M -l master-charset --description 'Charset of the file containing the document to translate.'
complete -c po4a-gettextize -s l -l localized --description 'File containing the localized (translated) document.'
complete -c po4a-gettextize -s L -l localized-charset --description 'Charset of the file containing the localized document.'
complete -c po4a-gettextize -s p -l po --description 'File where the message catalog should be written.'
complete -c po4a-gettextize -s o -l option --description 'Extra option(s) to pass to the format plugin.'
complete -c po4a-gettextize -s h -l help --description 'Show a short help message.'
complete -c po4a-gettextize -l help-format --description 'List the documentation formats understood by po4a.'
complete -c po4a-gettextize -s V -l version --description 'Display the version of the script and exit.'
complete -c po4a-gettextize -s v -l verbose --description 'Increase the verbosity of the program.'
complete -c po4a-gettextize -s d -l debug --description 'Output some debugging information.'
complete -c po4a-gettextize -l msgid-bugs-address --description 'Set the report address for msgid bugs.'
complete -c po4a-gettextize -l copyright-holder --description 'Set the copyright holder in the \\s-1POT\\s0 header.'
complete -c po4a-gettextize -l package-name --description 'Set the package name for the \\s-1POT\\s0 header.'
complete -c po4a-gettextize -l package-version --description 'Set the package version for the \\s-1POT\\s0 header.'

