# po4a-display-pod
# Autogenerated from man page /usr/local/share/man/man1/po4a-display-pod.1.gz
complete -c po4a-display-pod -s p --description 'The PO file containing the translations.'
complete -c po4a-display-pod -s m --description 'The original POD file used by po4a to generate PO file.'
complete -c po4a-display-pod -s o --description 'Some options to pass to po4a-translate(1).'

