# pspell-config
# Autogenerated from man page /usr/local/share/man/man1/pspell-config.1
complete -c pspell-config -l version --description 'outputs version information about the installed pspell.'
complete -c pspell-config -l datadir --description 'displays the data directory.'
complete -c pspell-config -l pkgdatadir --description 'displays the aspell package directory AUTHOR This manual page was written by …'

