# pstree
# Autogenerated from man page /usr/local/share/man/man1/pstree.1
complete -c pstree -s f --description 'Read input from file instead of running ps -kaxwwo user,pid,ppid,pgid,command.'
complete -c pstree -s g --description 'Use graphics chars for tree.  n = 1: IBM-850, n = 2: VT100, n = 3: UTF8.'
complete -c pstree -s l --description 'Show a maximum of n levels.'
complete -c pstree -s p --description 'Show only parents and descendants of the process pid.'
complete -c pstree -s s --description 'Show only parents and descendants of processes containing the string in their…'
complete -c pstree -s U --description 'Do not show branches containing only root processes.'
complete -c pstree -s u --description 'Show only parents and descendants of processes of user.'
complete -c pstree -s w --description 'Wide output, not truncated to terminal width.'

