# reorder
# Autogenerated from man page /usr/local/share/man/man1/reorder.1
complete -c reorder -s h -l help --description 'print this message and exit.'
complete -c reorder -s V -l version --description 'print version info and exit.'
complete -c reorder -s v -l verbose --description 'print verbose messages during execution.'
complete -c reorder -s d -l delim --description 'specifies delimiting string.'
complete -c reorder -s s -l swap --description 'specifies two fields to swap (ex: -s 1,3).'
complete -c reorder -s m -l move --description 'specifies a field to move to a new position (ex: -s 3,1).'
complete -c reorder -s f -l fields --description 'specifies fields to use to create a new string (ex: -f 3,4,1,5,2).'
complete -c reorder -s F -l field-labels --description 'a list of labels specifying the output field order.'

