# smicache
# Autogenerated from man page /usr/local/share/man/man1/smicache.1
complete -c smicache -s V --description 'Show the smicache version and exit.'
complete -c smicache -s h --description 'Show a help text and exit.'
complete -c smicache -s d --description 'Write fetched module file(s) to directory dir.'
complete -c smicache -s p --description 'Use the URL prefix prefix for fetching modules.'

