# smiquery
# Autogenerated from man page /usr/local/share/man/man1/smiquery.1
complete -c smiquery -s V -l version --description 'Show the smiquery version and exit.'
complete -c smiquery -s h -l help --description 'Show a help text and exit.  The help text lists all available commands.'
complete -c smiquery -s p -l preload --description 'Preload the module module before reading the main module.'

