# smistrip
# Autogenerated from man page /usr/local/share/man/man1/smistrip.1
complete -c smistrip -s V --description 'Show the smistrip version and exit.'
complete -c smistrip -s h --description 'Show a help text and exit.'
complete -c smistrip -s n --description 'Print only what would be extracted, but do not write any output file.'
complete -c smistrip -s d --description 'Write module file(s) to directory dir instead of the current working director…'
complete -c smistrip -s m --description 'Extract only the module module instead of all modules found in the input file…'

