# socat
# Autogenerated from man page /usr/local/share/man/man1/socat.1
complete -c socat -s '?' --description 'Print a help text to stdout describing command line options and available add…'
complete -c socat -o '??' --description 'Like -h, plus a list of the short names of all available address options.'
complete -c socat -o '???' --description 'Like -hh, plus a list of all available address option names.'
complete -c socat -s d --description 'Prints fatal, error, warning, and notice messages.'

