# subnetcalc
# Autogenerated from man page /usr/local/share/man/man1/subnetcalc.1
complete -c subnetcalc -s n --description 'Skip trying a reverse DNS lookup.'
complete -c subnetcalc -o uniquelocal --description 'Given an IPv6 address, the first 48 bits of the address are replaced by a ran…'
complete -c subnetcalc -o uniquelocalhq --description 'Like \\-uniquelocal, but using /dev/random instead on Linux systems for highes…'
complete -c subnetcalc -o nocolour --description 'Turns colourised output off.  El EXAMPLES -tag -width indent subnetcalc 132.'

