# subtotal
# Autogenerated from man page /usr/local/share/man/man1/subtotal.1
complete -c subtotal -s h -l help --description 'print this message and exit.'
complete -c subtotal -s V -l version --description 'print version info and exit.'
complete -c subtotal -s v -l verbose --description 'print verbose messages during execution.'
complete -c subtotal -s i -l input --description 'name of input file (stdin if not specified).'
complete -c subtotal -s d -l delim --description 'input delimiter (ascii 0xfe if not specified).'
complete -c subtotal -s o -l output --description 'name of output file (stdout if not specified).'
complete -c subtotal -s l -l start-line --description 'the first line of data - everything before it is printed as-is.'
complete -c subtotal -s k -l key --description '1-based column number for subtotal key.'
complete -c subtotal -s K -l key-label --description 'label of column for subtotal key.'
complete -c subtotal -s s -l sum --description 'list of 1-based column numbers to be subtotaled.'
complete -c subtotal -s S -l sum-labels --description 'list of column labels to be subtotaled.'

