# tapi-analyze
# Autogenerated from man page /Library/Developer/CommandLineTools/usr/share/man/man1/tapi-analyze.1
complete -c tapi-analyze -l target --description '.'
complete -c tapi-analyze -s o --description '.'
complete -c tapi-analyze -l sdkdb --description '.'
complete -c tapi-analyze -s v --description '.'
complete -c tapi-analyze -l app-info-output --description '.'
complete -c tapi-analyze -l pretty-json --description '.'

