# translate_field
# Autogenerated from man page /usr/local/share/man/man1/translate_field.1
complete -c translate_field -s h -l help --description 'print this message and exit.'
complete -c translate_field -s d -l delim --description 'field separator string (default: 0xfe).'
complete -c translate_field -s f -l field --description 'index of the field to translate.'
complete -c translate_field -s F -l Field-label --description 'column label of the field to translate.'
complete -c translate_field -s a -l append --description 'append the translated field after the original field.'
complete -c translate_field -s p -l prepend --description 'prepend the translated field before the original field.'
complete -c translate_field -s r -l replace --description 'replace the original field with the translated field.'
complete -c translate_field -s m -l map --description 'specifies a translation mapping for a possible field value (may be specified …'
complete -c translate_field -s e -l external --description 'specifies a file containing perl expressions which define mappings in the has…'
complete -c translate_field -s x -l xpression --description 'specifies a list of regular expressions to apply to the specified input field.'
complete -c translate_field -s k --description 'pass the first line of input through unmodified.'

