# tred
# Autogenerated from man page /usr/local/share/man/man1/tred.1
complete -c tred -s v --description 'Verbose output to stderr.'
complete -c tred -s r --description 'Print information of removed edges to stderr.'
complete -c tred -s '?' --description 'Print usage information.  OPERANDS The following operand is supported:.'

