# truncfield
# Autogenerated from man page /usr/local/share/man/man1/truncfield.1
complete -c truncfield -s h -l help --description 'print this message and exit.'
complete -c truncfield -s V -l version --description 'print version info and exit.'
complete -c truncfield -s d -l delimiter --description 'field-separator string.'
complete -c truncfield -s f -l field --description 'indexes of fields to be truncated.'
complete -c truncfield -s F -l field-labels --description 'labels of fields to be truncated.'
complete -c truncfield -s o -l output-file --description 'name of file to which output should be written.'
complete -c truncfield -s a -l append-file --description 'name of file to which output should be appended.'

