# unbound-control-setup
# Autogenerated from man page /usr/local/share/man/man8/unbound-control-setup.8
complete -c unbound-control-setup -s h --description 'Show the version and commandline option help.'
complete -c unbound-control-setup -s c --description 'The config file to read with settings.'
complete -c unbound-control-setup -s s --description 'IPv4 or IPv6 address of the server to contact.'
complete -c unbound-control-setup -s q --description 'quiet, if the option is given it does not print anything if it works ok.'

