# unbound-checkconf
# Autogenerated from man page /usr/local/share/man/man8/unbound-checkconf.8
complete -c unbound-checkconf -s h --description 'Show the version and commandline option help.'
complete -c unbound-checkconf -s f --description 'Print full pathname, with chroot applied to it.   Use with the -o option.'
complete -c unbound-checkconf -s o --description 'If given, after checking the config file the value of this option is  printed…'

