# unbound-host
# Autogenerated from man page /usr/local/share/man/man1/unbound-host.1
complete -c unbound-host -s r --description '.'
complete -c unbound-host -s h --description 'Show the version and commandline option help.'
complete -c unbound-host -s v --description 'Enable verbose output and it shows validation results, on every line.'
complete -c unbound-host -s d --description 'Enable debug output to stderr.'
complete -c unbound-host -s c --description 'Specify the class to lookup for, the default is IN the internet class.'
complete -c unbound-host -s t --description 'Specify the type of data to lookup.'
complete -c unbound-host -s y --description 'Specify a public key to use as trust anchor.'
complete -c unbound-host -s D --description 'Enables DNSSEC validation.'
complete -c unbound-host -s f --description 'Reads keys from a file.'
complete -c unbound-host -s F --description 'Reads keys from a BIND-style named. conf file.'
complete -c unbound-host -s C --description 'Uses the specified unbound. conf to prime libunbound (3).'
complete -c unbound-host -s 4 --description 'Use solely the IPv4 network for sending packets.'
complete -c unbound-host -s 6 --description 'Use solely the IPv6 network for sending packets.'

