# update-leap
# Autogenerated from man page /usr/local/share/man/man8/update-leap.8
complete -c update-leap -o '\\&?' --description 'Display usage information and exit.'
complete -c update-leap -o '\\&' --description 'Pass the extended usage information through a pager.'
complete -c update-leap -s v --description 'Output version of program and exit.'

