# vdecmd
# Autogenerated from man page /usr/local/share/man/man1/vdecmd.1
complete -c vdecmd -s s --description 'management socket path (default is /var/run/unixcmd).'
complete -c vdecmd -s f --description 'configuration path (default is /etc/unixcmd).'
complete -c vdecmd -s v --description 'run parse machine in debug mode.'

