# vdeq
# Autogenerated from man page /usr/local/share/man/man1/vdeq.1
complete -c vdeq -l mod --description 'octalmode,  specify the mode for comm socket. br.'
complete -c vdeq -o sock --description 'socketpath,  specify the UNIX socket to be used by local programs for joining…'
complete -c vdeq -s h -o help -l help --description 'print a Usage help.  NOTE Qemu has changed its syntax for networking (cvs Nov.'

