# wcmgr
# Autogenerated from man page /usr/local/share/man/man1/wcmgr.1
complete -c wcmgr -s h --description 'Display all available command line options and exit.'
complete -c wcmgr -s v --description 'Be verbose.'
complete -c wcmgr -s V --description 'Display the program version and exit.'
complete -c wcmgr -s a -s n --description 'Add a new record to the cache file.'
complete -c wcmgr -s c --description 'Create a new cache file.'
complete -c wcmgr -s d --description 'Delete a record from the cache file using the specified address.'
complete -c wcmgr -s f --description 'Find and display information for address from the cache file.'
complete -c wcmgr -s i --description 'Import data into the cache file from the file name.'
complete -c wcmgr -s l --description 'List the contents of the cache file.'
complete -c wcmgr -s p --description 'Purge the cache file of entries older than num days.'
complete -c wcmgr -s s -s t --description 'Display cache file information/statistics.'
complete -c wcmgr -s x --description 'Export data from a cache file to a tab delimited text file named name.'

