# xml2csv
# Autogenerated from man page /usr/local/share/man/man1/xml2csv.1
complete -c xml2csv -s e --description 'Specify input character encoding.  By default, ISO-8859-1 is assumed.'
complete -c xml2csv -s f --description 'Read CSV input from the specified file.'
complete -c xml2csv -s i --description 'Ignore the very first CSV record in the input (typically contains column name…'
complete -c xml2csv -s q --description 'Specify an alternate CSV column quote character.'
complete -c xml2csv -s s --description 'Specify an alternate CSV column separator character.'
complete -c xml2csv -s h --description 'Output usage message and exit.'
complete -c xml2csv -s v --description 'Output version information and exit.'
complete -c xml2csv -s x --description 'Convert the CSV input into an XML document.'
complete -c xml2csv -s X --description 'Same as x, but it also causes the values in the first row to be used as the X…'

