# Oh My Fish configuration
# This file is automatically generated by Oh My Fish

# Set Oh My Fish path
set -g OMF_PATH $HOME/.local/share/omf

# Load Oh My Fish
if test -f $OMF_PATH/init.fish
    source $OMF_PATH/init.fish
end

# Note: Theme and plugins will be configured after Oh My Fish is properly loaded
# Run these commands manually after Fish starts:
# omf theme agnoster
# omf install fzf
# omf install z
# omf install git
